#!/usr/bin/env bash 
# fortune-maths
set -e

FORTUNE="/usr/games/fortune"
PROOFS="/usr/local/share/games/fortunes/proofs"
[ -x $FORTUNE ] || ( echo "E: Please install package 'fortune-mod'."; false )
LANG="*"
NUM=1000
LATEX_FLAG=0
APROPOS_ARG=""
PROOF_FLAG=0
SHOW_FLAG=0
CODE=""

optspec="a:n:lspL:h"
while getopts "$optspec" optchar; do
    case "${optchar}" in
	# long options
        h)
            echo "usage: $0 [[-a <pattern>] | [[[-l [-p [-L <lang>] [-n <num>]]] | [-s]] [<thm-code>]]]" >&2
            exit 2
            ;;
        a)
            APROPOS_ARG="${OPTARG}"
            ;;
        l)
            LATEX_FLAG=1
            ;;
        p)
            PROOF_FLAG=1
            ;;
        s)
            SHOW_FLAG=1
            ;;
        n)
            NUM="${OPTARG}"
            ;;
        L)
            LANG="${OPTARG}"
            ;;
        *)
            if [ "$OPTERR" != 1 ] || [ "${optspec:0:1}" = ":" ]; then
                echo "Non-option argument: '-${OPTARG}'" >&2
            fi
            ;;
    esac
done

DICT="50% logic 50% models"
DATA=`$FORTUNE $DICT`
FILENAME=`echo "${DATA}" | head -n +1`
TEXT=`echo "${DATA}" | tail -n +2`
if [ "$LATEX_FLAG" -eq 1 ]; then
    # output latex 
    printf '\\documentclass{article}\n'
    printf '\\begin{document}\n'
    printf '\\section*{The Theorem}\n'
    cat  "$PROOFS/$FILENAME.tex"
    if [ "$PROOF_FLAG" -eq 1 ]; then
        # statement + proof
        count=1
        proofs_list="$(find $PROOFS -type f,l -name "$FILENAME.$LANG.*.tex" -print)"
        if [ `echo "${proofs_list}" | sed '/^\s*$/d' |  wc -l` -gt 0 ]; then
            printf '\\section*{Proofs}\n'
            printf '\\begin{itemize}\n'
            for f in `echo "${proofs_list}" | head -n $NUM`; do
                printf "\\\\item \\\\textbf{proof $(( count++ ))} "
                cat $f
            done
            printf '\\end{itemize}\n'
        fi
    fi
    printf '\\end{document}\n'
elif [ "$APROPOS_ARG" != "" ]; then
    $FORTUNE -m "$APROPOS_ARG" $DICT 2> /dev/null | tail -n +2 | head -n -1
else 
    if [ "$PROOF_FLAG" -eq 1 ]; then 
        echo "usage: $0 [[-a <pattern>] | [[[-l [-p [-L <lang>] [-n <num>]]] | [-s]] [<thm-code>]]]" >&2
        exit 2
    fi
    if [ "$SHOW_FLAG" -eq 1 ]; then echo "<${FILENAME}>"; fi
    echo  "${TEXT}"
fi
